const GET_CARDS = 'GET_CARDS';
const GET_CARD = 'GET_CARD';
const ADD_CARD = 'ADD_CARD';
const UPDATE_CARD = 'UPDATE_CARD';
const REMOVE_CARD = 'REMOVE_CARD';

export { GET_CARDS, GET_CARD, ADD_CARD, UPDATE_CARD, REMOVE_CARD };
