const GET_COLLECTIONS = 'GET_COLLECTIONS';
const GET_COLLECTION = 'GET_COLLECTION';
const GET_COLLECTION_CARDS = 'GET_COLLECTION_CARDS';
const REMOVE_COLLECTION = 'REMOVE_COLLECTION';

export { GET_COLLECTIONS, GET_COLLECTION, GET_COLLECTION_CARDS, REMOVE_COLLECTION };
